#!/usr/bin/env python
import cairo
import yaml

import argparse as ap
from datetime import datetime
from datetime import timedelta
from glob import glob
from importlib import import_module
import logging
from os import makedirs
from os.path import basename, dirname, join
from time import sleep

from gpsrenda.datasources import FitDataSource
from gpsrenda.globals import globals, set_globals
from gpsrenda.video import moviepy

def renda(video_paths, data_path, time_offset, config_path, preview):
    logging.basicConfig(format='%(asctime)s %(levelname)s[%(name)s] %(message)s')

    logger = logging.getLogger(__file__)
    logger.setLevel(logging.DEBUG)
    logger.debug("Begin")

    with open(config_path, 'r') as config_file:
        config_data = yaml.safe_load(config_file)

    set_globals(config_data.get('globals', {}))

    data_source = FitDataSource(data_path, config=config_data.get('data', {}))

    widgets = []
    widget_module = import_module('gpsrenda.widgets.widgets')
    for widget_spec in config_data['widgets']:
        try:
            widget_type = widget_spec.pop('type')
            widget_class = getattr(widget_module, widget_type+'Widget')
            widget = widget_class(data_source=data_source, **widget_spec)
            widgets.append(widget)
        except Exception as e:
            print(f"while trying to create a widget of type {widget_type}:")
            raise

    def make_frame(ctx, t):
        for widget in widgets:
            widget.render(ctx, t - time_offset)
    engine = moviepy.RenderEngineMoviepy(make_frame)

    for video_path in video_paths:
        if preview:
            engine.preview(video_path)
        else:
            out_dir = join(dirname(video_path), 'rendered')
            try:
                makedirs(out_dir)
            except FileExistsError:
                pass

            output_file = join(out_dir, basename(video_path))

            engine.render(video_path, output_file)

if __name__ == "__main__":
    parser = ap.ArgumentParser()
    parser.add_argument('video_pattern', type=str, nargs='+', help="Path or glob pointing to video file(s)")
    parser.add_argument('data_path', type=str, help="Path to the activity data file")
    parser.add_argument('config_path', type=str, help="Path to the gauges setup and config file")
    parser.add_argument('-t', '--time-offset', dest='time_offset', type=float, default=0.,
                        help="How far ahead (+) or behind (-) is the video compared to the fit file's internal timestamps")
    parser.add_argument('-p', '--preview', dest='preview', action='store_true', default=False)

    args = parser.parse_args()
    video_paths = sum([glob(pattern) for pattern in args.video_pattern], [])
    time_offset = args.time_offset #timedelta(seconds=args.time_offset)

    renda(video_paths, args.data_path, time_offset, args.config_path, args.preview)
